---
Name: newsgrid
---


SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'restruct/silverstripe-newsgrid:client/dist/css/newsgridpages.css'

Restruct\SilverStripe\NewsGrid\NewsGridHolder:
  extensions:
    - Restruct\SilverStripe\NewsGrid\Extensions\CustomLumberjack

Restruct\SilverStripe\NewsGrid\NewsGridPage:
  show_in_sitetree: false
  extensions:
    - Restruct\SilverStripe\FeaturedImages\FeaturedImageExtension

---
Name: newsgridembargo
Only:
  classexists: Restruct\SilverStripe\SoftScheduler\EmbargoExpirySchedulerExtension
---
Restruct\SilverStripe\NewsGrid\NewsGridPage:
  extensions:
    - Restruct\SilverStripe\SoftScheduler\EmbargoExpirySchedulerExtension

---
Name: newsgridfilterable
Only:
  classexists: Restruct\SilverStripe\FilterableArchive\FilterableArchiveHolderControllerExtension
---
Restruct\SilverStripe\NewsGrid\NewsGridHolder:
  extensions:
    - Restruct\SilverStripe\FilterableArchive\FilterableArchiveHolderExtension
  pagination_control_tab: "Root.Structure"
  #pagination_insert_before: "SubPages"
  managed_object_class: Restruct\SilverStripe\NewsGrid\NewsGridPage
  managed_object_date_field: "Date"

Restruct\SilverStripe\NewsGrid\NewsGridHolderController:
  extensions:
    - Restruct\SilverStripe\FilterableArchive\FilterableArchiveHolderControllerExtension

Restruct\SilverStripe\NewsGrid\NewsGridPage:
  extensions:
    - Restruct\SilverStripe\FilterableArchive\FilterableArchiveItemExtension

Restruct\SilverStripe\FilterableArchive\FilterableCategory:
  extensions:
    - Restruct\SilverStripe\NewsGrid\Extensions\FilterableCategoryExtension

