---
Name: newsgrid
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'restruct/silverstripe-newsgrid:client/css/newsgridpages.css'

Restruct\SilverStripe\NewsGrid\NewsGridHolder:
#  extensions:
#    - Restruct\SilverStripe\NewsGrid\Extensions\CustomLumberjack
#    - Restruct\Silverstripe\GridFieldPages\GridFieldPageHolderExtension
#  add_default_gridfield: true
  extensions:
    - Restruct\Silverstripe\AdminTweaks\Extensions\SelectiveLumberjack
  hide_from_cms_tree:
    - Restruct\SilverStripe\NewsGrid\NewsGridPage
  allowed_children:
    - Restruct\SilverStripe\NewsGrid\NewsGridPage

Restruct\SilverStripe\NewsGrid\NewsGridPage:
  extensions:
    - Restruct\SilverStripe\FeaturedImages\FeaturedImageExtension
# The below are now optional and will be applied if their class exists:
#    - Restruct\SilverStripe\SoftScheduler\EmbargoExpiryExtension
#    - Restruct\Silverstripe\GridFieldPages\GridFieldPageExtension


---
Name: newsgridfilterable
Only:
  classexists: Restruct\SilverStripe\FilterableArchive\Extensions\HolderControllerExtension
---
Restruct\SilverStripe\NewsGrid\NewsGridHolder:
  extensions:
    - Restruct\SilverStripe\FilterableArchive\Extensions\HolderExtension
  pagination_control_tab: "Root.Filtering"
  #pagination_insert_before: "SubPages"
  managed_object_class: Restruct\SilverStripe\NewsGrid\NewsGridPage
  managed_object_date_field: "Date"
  # NOTE: change these to true-ish to also filter newsitems by categories and/or tags
#  categories_active: false
#  tags_active: false

Restruct\SilverStripe\NewsGrid\NewsGridHolderController:
  extensions:
    - Restruct\SilverStripe\FilterableArchive\Extensions\HolderControllerExtension

Restruct\SilverStripe\NewsGrid\NewsGridPage:
  extensions:
    - Restruct\SilverStripe\FilterableArchive\Extensions\ItemExtension

#Restruct\SilverStripe\FilterableArchive\FilterableCategory:
#  extensions:
#    - Restruct\SilverStripe\NewsGrid\Extensions\FilterableCategoryExtension


---
Name: newsgridembargo
Only:
  classexists: Restruct\SilverStripe\SoftScheduler\EmbargoExpiryExtension
---
Restruct\SilverStripe\NewsGrid\NewsGridPage:
  extensions:
    - Restruct\SilverStripe\SoftScheduler\EmbargoExpiryExtension
